// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chatpb/chat-service.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatpb_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_chatpb_chat_service_proto protoreflect.FileDescriptor

const file_chatpb_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x19chatpb/chat-service.proto\x12\x06chatpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2C\n" +
	"\vChatService\x124\n" +
	"\x04Chat\x12\x13.chatpb.ChatMessage\x1a\x13.chatpb.ChatMessage(\x010\x01B\x14Z\x12internal/pb/chatpbb\x06proto3"

var (
	file_chatpb_chat_service_proto_rawDescOnce sync.Once
	file_chatpb_chat_service_proto_rawDescData []byte
)

func file_chatpb_chat_service_proto_rawDescGZIP() []byte {
	file_chatpb_chat_service_proto_rawDescOnce.Do(func() {
		file_chatpb_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatpb_chat_service_proto_rawDesc), len(file_chatpb_chat_service_proto_rawDesc)))
	})
	return file_chatpb_chat_service_proto_rawDescData
}

var file_chatpb_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chatpb_chat_service_proto_goTypes = []any{
	(*ChatMessage)(nil),           // 0: chatpb.ChatMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_chatpb_chat_service_proto_depIdxs = []int32{
	1, // 0: chatpb.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: chatpb.ChatService.Chat:input_type -> chatpb.ChatMessage
	0, // 2: chatpb.ChatService.Chat:output_type -> chatpb.ChatMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatpb_chat_service_proto_init() }
func file_chatpb_chat_service_proto_init() {
	if File_chatpb_chat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatpb_chat_service_proto_rawDesc), len(file_chatpb_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatpb_chat_service_proto_goTypes,
		DependencyIndexes: file_chatpb_chat_service_proto_depIdxs,
		MessageInfos:      file_chatpb_chat_service_proto_msgTypes,
	}.Build()
	File_chatpb_chat_service_proto = out.File
	file_chatpb_chat_service_proto_goTypes = nil
	file_chatpb_chat_service_proto_depIdxs = nil
}
